name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      prs: '[{"labels": ["@hoge/hoge", "@hoge/fuga"]}, {"labels": ["@fuga/fuga"]}]'
    steps:
      - name: show all
        shell: bash
        run: |
          echo "all"
          echo ${{ fromJSON(env.prs) }}
      - name: show all labels
        shell: bash
        run: |
          echo "all labels"
          echo ${{ fromJSON(env.prs) }} | jq -c '[.[].labels[]]'



