name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      prs: '[{"labels": ["@hoge/hoge", "@hoge/fuga"]}, {"labels": "@fuga/fuga"}]'
    steps:
      - name: show all
        shell: bash
        run: |
          echo "all"
          echo ${{ fromJSON(env.prs) }}
      - name: show all labels
        shell: bash
        run: |
          echo "all labels"
          for pr in ${{ fromJSON(env.prs) }}; do
            echo $pr
            echo $pr.labels
          done



